"""Initial migration

Revision ID: bd5f91232614
Revises: 
Create Date: 2026-05-25 13:09:18.760276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'bd5f91232614'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('retrieval_summary', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('retrieval_summary', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('fts_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_metadata',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('issuer', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.Text(), nullable=True),
    sa.Column('facility_name', sa.Text(), nullable=True),
    sa.Column('species', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('inspection_date', sa.DateTime(), nullable=True),
    sa.Column('inspector_name', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.Text(), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('model', sa.Text(), server_default='text-embedding-3-small', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.create_index('idx_chunks_document_id', 'chunks', ['document_id'])
    op.create_index('idx_chunks_fts', 'chunks', ['fts_vector'], postgresql_using='gin')
    op.create_index('idx_embeddings_chunk_id', 'embeddings', ['chunk_id'])
    
    op.execute("""
        CREATE INDEX idx_embeddings_vector ON embeddings
        USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION chunks_fts_update() RETURNS trigger AS $$
        BEGIN
            NEW.fts_vector :=
                setweight(to_tsvector('english', coalesce(NEW.retrieval_summary, '')), 'A') ||
                setweight(to_tsvector('english', coalesce(NEW.raw_text, '')), 'B');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER chunks_fts_trigger
            BEFORE INSERT OR UPDATE ON chunks
            FOR EACH ROW EXECUTE FUNCTION chunks_fts_update();
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS chunks_fts_trigger ON chunks;")
    op.execute("DROP FUNCTION IF EXISTS chunks_fts_update();")
    op.drop_index('idx_embeddings_vector', table_name='embeddings', postgresql_using='ivfflat')
    op.drop_index('idx_embeddings_chunk_id', table_name='embeddings')
    op.drop_index('idx_chunks_fts', table_name='chunks', postgresql_using='gin')
    op.drop_index('idx_chunks_document_id', table_name='chunks')

    op.drop_table('embeddings')
    op.drop_table('document_metadata')
    op.drop_table('chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###
